title: Researcher
url: "https://aakritikumar.com"
baseurl: "/researcher"

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/aakriti1kumar"
footer_text: ""

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "CV"
   link: "CV.pdf"
 - name: "Contact"
   link: "contact"
 - name: "Projects"
   link: "projects"
 - name: "Miscellaneous"
   link: "miscellaneous"

