title: Aakriti Kumar
url: "https://aakritikumar.com"
baseurl: ""

markdown: kramdown

tracking_id: #

footer: no
footer_url: "https://github.com/aakriti1kumar"
footer_text: ""

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index"
 - name: "CV"
   link: "CV.pdf"
 - name: "Publications"
   link: "pubs"
 - name: "Projects"
   link: "projects"
 - name: "Other Things"
   link: "Otherthings"

